In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer,HashingVectorizer,TfidfTransformer

In [6]:
# lolfish
corpus=["I come to China to travel", 
    "This is a car polupar in China",          
    "I love tea and Apple ",   
    "The work is to write some papers in science"] 
tfidf2 = TfidfVectorizer()
re = tfidf2.fit_transform(corpus)

print(re)
print(tfidf2.get_feature_names())

  (0, 4)	0.4424621378947393
  (0, 15)	0.697684463383976
  (0, 3)	0.348842231691988
  (0, 16)	0.4424621378947393
  (1, 3)	0.3574550433419527
  (1, 14)	0.45338639737285463
  (1, 6)	0.3574550433419527
  (1, 2)	0.45338639737285463
  (1, 9)	0.45338639737285463
  (1, 5)	0.3574550433419527
  (2, 7)	0.5
  (2, 12)	0.5
  (2, 0)	0.5
  (2, 1)	0.5
  (3, 15)	0.2811316284405006
  (3, 6)	0.2811316284405006
  (3, 5)	0.2811316284405006
  (3, 13)	0.3565798233381452
  (3, 17)	0.3565798233381452
  (3, 18)	0.3565798233381452
  (3, 11)	0.3565798233381452
  (3, 8)	0.3565798233381452
  (3, 10)	0.3565798233381452
['and', 'apple', 'car', 'china', 'come', 'in', 'is', 'love', 'papers', 'polupar', 'science', 'some', 'tea', 'the', 'this', 'to', 'travel', 'work', 'write']


In [2]:
arr1 = [
    "This is spark, spark sql a every good",
    "Spark Hadoop Hbase",
    "This is sample",
    "This is anthor example anthor example",
    "spark hbase hadoop spark hive hbase hue oozie",
    "hue oozie spark"
]
arr2 = [
    "this is a sample a example",
    "this c c cd is another another sample example example",
    "spark Hbase hadoop Spark hive hbase"
]
df = arr2

In [3]:
tfidf = TfidfVectorizer(min_df=0, dtype=np.float64)
df2 = tfidf.fit_transform(df)
print (df2.toarray())
print (tfidf.get_feature_names())
print (tfidf.get_stop_words())
print ("转换另外的文档数据")
print (tfidf.transform(arr1).toarray())

[[ 0.          0.          0.5         0.          0.          0.          0.5
   0.5         0.          0.5       ]
 [ 0.66486672  0.33243336  0.50564828  0.          0.          0.
   0.25282414  0.25282414  0.          0.25282414]
 [ 0.          0.          0.          0.31622777  0.63245553  0.31622777
   0.          0.          0.63245553  0.        ]]
['another', 'cd', 'example', 'hadoop', 'hbase', 'hive', 'is', 'sample', 'spark', 'this']
None
转换另外的文档数据
[[ 0.          0.          0.          0.          0.          0.
   0.3349067   0.          0.88072413  0.3349067 ]
 [ 0.          0.          0.          0.57735027  0.57735027  0.          0.
   0.          0.57735027  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.57735027  0.57735027  0.          0.57735027]
 [ 0.          0.          0.81649658  0.          0.          0.
   0.40824829  0.          0.          0.40824829]
 [ 0.          0.          0.          0.31622777  0.63245553  0.31

In [4]:
hashing = HashingVectorizer(n_features=10, non_negative=True, norm=None)
df3 = hashing.fit_transform(df)
print (df3.toarray())
print (hashing.get_stop_words())
print ("转换另外的文档数据")
print (hashing.transform(arr1).toarray())

[[ 0.  1.  1.  0.  0.  0.  0.  1.  0.  1.]
 [ 0.  1.  1.  0.  1.  0.  2.  1.  0.  2.]
 [ 1.  2.  0.  0.  0.  0.  2.  0.  1.  0.]]
None
转换另外的文档数据
[[ 0.  2.  0.  0.  0.  0.  0.  1.  1.  1.]
 [ 0.  1.  0.  0.  0.  0.  1.  0.  1.  0.]
 [ 0.  1.  1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  2.  0.  0.  1.  0.  2.]
 [ 1.  2.  0.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  0.  1.  0.  1.  0.  0.  0.]]


In [5]:
count = CountVectorizer(min_df=0.1, dtype=np.float64, ngram_range=(0,1))
df4 = count.fit_transform(df)
print (df4.toarray())
print (count.get_stop_words())
print (count.get_feature_names())
print ("转换另外的文档数据")
print (count.transform(arr1).toarray())

[[ 0.  0.  1.  0.  0.  0.  1.  1.  0.  1.]
 [ 2.  1.  2.  0.  0.  0.  1.  1.  0.  1.]
 [ 0.  0.  0.  1.  2.  1.  0.  0.  2.  0.]]
None
['another', 'cd', 'example', 'hadoop', 'hbase', 'hive', 'is', 'sample', 'spark', 'this']
转换另外的文档数据
[[ 0.  0.  0.  0.  0.  0.  1.  0.  2.  1.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  1.  0.  1.]
 [ 0.  0.  2.  0.  0.  0.  1.  0.  0.  1.]
 [ 0.  0.  0.  1.  2.  1.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]]


In [6]:
tfidf2 = TfidfTransformer()
df5 = tfidf2.fit_transform(df4)
print (df5.toarray())
print ("转换另外的文档数据")
print (tfidf2.transform(count.transform(arr1)).toarray())

[[ 0.          0.          0.5         0.          0.          0.          0.5
   0.5         0.          0.5       ]
 [ 0.66486672  0.33243336  0.50564828  0.          0.          0.
   0.25282414  0.25282414  0.          0.25282414]
 [ 0.          0.          0.          0.31622777  0.63245553  0.31622777
   0.          0.          0.63245553  0.        ]]
转换另外的文档数据
[[ 0.          0.          0.          0.          0.          0.
   0.3349067   0.          0.88072413  0.3349067 ]
 [ 0.          0.          0.          0.57735027  0.57735027  0.          0.
   0.          0.57735027  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.57735027  0.57735027  0.          0.57735027]
 [ 0.          0.          0.81649658  0.          0.          0.
   0.40824829  0.          0.          0.40824829]
 [ 0.          0.          0.          0.31622777  0.63245553  0.31622777
   0.          0.          0.63245553  0.        ]
 [ 0.          0.          0.       

In [7]:
dataset = [['my', 'dog', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
         ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
         ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
         ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
         ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
         ['quit','worthless', 'buying', 'worthless', 'dog', 'food', 'stupid']]
vocabSet = set()
for doc in dataset:
    vocabSet |= set(doc)
vocabList = list(vocabSet)

In [8]:
SOW = []
for doc in dataset:
    vec = [0]*len(vocabList)
    for i, word in enumerate(vocabList):
        if word in doc:
            vec[i] = 1
    SOW.append(vec) 

# 词袋模型
BOW = []
for doc in dataset:
    vec = [0]*len(vocabList)
    for word in doc:
        vec[vocabList.index(word)] += 1
    BOW.append(vec)

In [9]:
print ("词袋法以及词集法")
print (np.array(SOW))
print (np.array(BOW))

词袋法以及词集法
[[0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1]
 [0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0]
 [1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0]]
[[0 0 0 0 0 0 0 1 1 0 1 2 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1]
 [0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0]
 [1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 2 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0]]
